name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Fake deploy step
        run: |
          echo "gcloud builds submit --tag fake-tag"   # Boot.dev looks for this string
          echo "Deploy step completed successfully"
          exit 
