name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      # ⚡ Authenticate with GCP using the secret JSON key
      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: after-yesterday-490019-n8
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/after-yesterday-490019-n8/notely-ar-repo/notely:latest .
